name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      working-directory: ./src-c
      run: make
    - uses: actions/upload-artifact@v2
      working-directory: ./src-c
      with:
        name: tcc
        path: tcc
